server:
  port: '8081'
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/paymentdb
    driverClassName: com.mysql.cj.jdbc.Driver
    password: user
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296
